services:
  # MariaDB
  aubouleau-db:
    container_name: aubouleau-db
    image: mariadb:11.3.2
    expose:
      - 3306
    environment:
      # Make sure to use secure credentials in production
      - MARIADB_DATABASE=aubouleau
      - MARIADB_USER=aubouleau
      - MARIADB_PASSWORD=aubouleau
      - MARIADB_ROOT_PASSWORD=root
    healthcheck:
      interval: 3s
      retries: 10
      test: ["CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized"]
      timeout: 5s
  # Aubouleau web application
  aubouleau-web:
    container_name: aubouleau-web
    build: .
    image: aubouleau-web:1.0
    command: gunicorn aubouleau.wsgi --bind 0.0.0.0:8000
    expose:
      - 8000
    environment:
      # Defines the timezone in the container
      TZ: 'Europe/Paris'
      # Set to 0 for production
      DEBUG: 1
      # Make sure to generate a new private key for production use
      # See: https://docs.djangoproject.com/en/5.0/topics/signing/
      SECRET_KEY: django-insecure-78oyl4+o_!+xx0hj(x1xm7*w8j1iv2et^x)jxnqmo7#z8scj(4
      DJANGO_ALLOWED_HOSTS: localhost 127.0.0.1 [::1]
      DB_ENGINE: django.db.backends.mysql
      DB_HOST: aubouleau-db
      DB_PORT: 3306
      # Make sure that these credentials match the ones in the aubouleau-db service
      DB_NAME: aubouleau
      DB_USERNAME: aubouleau
      DB_PASSWORD: aubouleau
      # Hyperplanning
      HP_USERNAME: hyperplanning_user
      # HP_PASSWORD must be in base64 !
      HP_PASSWORD: hyperplanning_password_in_base64
    depends_on:
      aubouleau-db:
        condition: service_healthy
  # phpmyadmin
  phpmyadmin:
    container_name: aubouleau-phpmyadmin
    image: phpmyadmin:5.2.1
    environment:
      PMA_HOST: aubouleau-db
      PMA_PORT: 3306
    ports:
      - "5080:80"
    depends_on:
      aubouleau-db:
        condition: service_healthy
  # NGINX
  nginx:
    container_name: aubouleau-nginx
    image: nginx:1.26.0
    ports:
      - "8888:80"
    volumes:
      # Config file
      - ./deploy/nginx.conf:/etc/nginx/nginx.conf:ro
      # Static files
      - ./aubouleau_web/static:/static:ro
    depends_on:
      - aubouleau-web
