# Generated by Django 5.0.6 on 2024-05-10 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(verbose_name='Creation timestamp')),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Floor number')),
                ('name', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(verbose_name='Creation timestamp')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aubouleau_web.building')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(verbose_name='Creation timestamp')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aubouleau_web.floor')),
            ],
        ),
    ]
